/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.1.5.0                                               */
/*  Date (dd.mm.yyyy): 24. 3.2021   Time (hh:mm): 17:26                        */
/*******************************************************************************/


#ifndef _GUIX_SIMPLE_HONBOW_DISP_RESOURCES_H_
#define _GUIX_SIMPLE_HONBOW_DISP_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define HONBOW_DISP 0
#define HONBOW_DISP_COLOR_FORMAT GX_COLOR_FORMAT_565RGB
#define HONBOW_DISP_X_RESOLUTION 320
#define HONBOW_DISP_Y_RESOLUTION 360
#define HONBOW_DISP_THEME_1 0
#define HONBOW_DISP_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define LANGUAGE_CHINESE 1
#define LANGUAGE_GERMAN 2
#define HONBOW_DISP_LANGUAGE_TABLE_SIZE 3

/* Color ID definitions                                                        */

#define GX_COLOR_ID_BLUE 29
#define GX_COLOR_ID_GRAY 30
#define GX_COLOR_ID_GRAY1 31
#define GX_COLOR_ID_BLUE1 32
#define GX_COLOR_ID_BLACK 33
#define GX_COLOR_ID_WHITE 34
#define GX_COLOR_ID_SILVERY_GRAY 35
#define GX_COLOR_ID_MILK_WHITE 36
#define GX_COLOR_ID_LIGHT_GRAY 37
#define GX_COLOR_ID_HONBOW_GREEN 38
#define GX_COLOR_ID_HONBOW_BLUE 39
#define GX_COLOR_ID_HONBOW_ORANGE 40
#define GX_COLOR_ID_HONBOW_YELLOW 41
#define HONBOW_DISP_COLOR_TABLE_SIZE 42

/* Font ID definitions                                                         */

#define GX_FONT_ID_SIZE_26 4
#define GX_FONT_ID_SIZE_30 5
#define HONBOW_DISP_FONT_TABLE_SIZE 6

/* Pixelmap ID definitions                                                     */

#define GX_PIXELMAP_ID_APP_COMPASS_ARROW 5
#define GX_PIXELMAP_ID_APP_COMPASS_LITTLE 6
#define GX_PIXELMAP_ID_APP_COMPASS_MAIN 7
#define GX_PIXELMAP_ID_APP_COMPASS_SMALL 8
#define GX_PIXELMAP_ID_APP_LIST_ICON_120_OVERLAY 9
#define GX_PIXELMAP_ID_APP_LIST_ICON_90_OVERLAY 10
#define GX_PIXELMAP_ID_APP_LIST_ICON_ALARM_90_90 11
#define GX_PIXELMAP_ID_APP_LIST_ICON_ALARM_BREATHE_90_90 12
#define GX_PIXELMAP_ID_APP_LIST_ICON_BLOOD_OXYGEN_90_90 13
#define GX_PIXELMAP_ID_APP_LIST_ICON_COMPASS_90_90 14
#define GX_PIXELMAP_ID_APP_LIST_ICON_HEART_90_90 15
#define GX_PIXELMAP_ID_APP_LIST_ICON_MUSIC_90_90 16
#define GX_PIXELMAP_ID_APP_LIST_ICON_REMIND_90_90 17
#define GX_PIXELMAP_ID_APP_LIST_ICON_SETTING_90_90 18
#define GX_PIXELMAP_ID_APP_LIST_ICON_SPORT_90_90 19
#define GX_PIXELMAP_ID_APP_LIST_ICON_STOPWATCH_90_90 20
#define GX_PIXELMAP_ID_APP_LIST_ICON_TIMER_90_90 21
#define GX_PIXELMAP_ID_APP_LIST_ICON_TODAY_OVERVIEW_90_90 22
#define GX_PIXELMAP_ID_CONTROL_CENTER_BRIGHTNESS 23
#define GX_PIXELMAP_ID_CONTROL_CENTER_BRIGHT_SCREEN_OFF 24
#define GX_PIXELMAP_ID_CONTROL_CENTER_BRIGHT_SCREEN_ON 25
#define GX_PIXELMAP_ID_CONTROL_CENTER_DO_NOT_DISTURB 26
#define GX_PIXELMAP_ID_CONTROL_CENTER_LINK 27
#define GX_PIXELMAP_ID_CONTROL_CENTER_LINK_OFF 28
#define GX_PIXELMAP_ID_CONTROL_CENTER_NIGHT 29
#define GX_PIXELMAP_ID_CONTROL_CENTER_SET_UP 30
#define GX_PIXELMAP_ID_DOT 31
#define GX_PIXELMAP_ID_STEPS 32
#define GX_PIXELMAP_ID_SWITCH_ACTIVE 33
#define GX_PIXELMAP_ID_SWITCH_BG 34
#define GX_PIXELMAP_ID_SWITCH_DISACTIVE 35
#define GX_PIXELMAP_ID_WIFI 36
#define GX_PIXELMAP_ID_WF_BG 37
#define GX_PIXELMAP_ID_WF_DOT_IMG 38
#define GX_PIXELMAP_ID_WF_HOUR_POINTER 39
#define GX_PIXELMAP_ID_WF_MIN_POINTER 40
#define GX_PIXELMAP_ID_WF_SEC_POINTER 41
#define GX_PIXELMAP_ID_WF_THUMB 42
#define HONBOW_DISP_PIXELMAP_TABLE_SIZE 43

/* String Ids                                                                  */

#define GX_STRING_ID_AM 1
#define GX_STRING_ID_PM 2
#define HONBOW_DISP_STRING_TABLE_SIZE 3

#endif                                       /* sentry                         */
