/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.1.0.0                                               */
/*  Date (dd.mm.yyyy): 26. 1.2021   Time (hh:mm): 15:59                        */
/*******************************************************************************/


#ifndef _GUIX_SIMPLE_MAIN_DISPLAY_RESOURCES_H_
#define _GUIX_SIMPLE_MAIN_DISPLAY_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define MAIN_DISPLAY 0
#define MAIN_DISPLAY_COLOR_FORMAT GX_COLOR_FORMAT_565RGB
#define MAIN_DISPLAY_X_RESOLUTION 360
#define MAIN_DISPLAY_Y_RESOLUTION 360
#define MAIN_DISPLAY_THEME_1 0
#define MAIN_DISPLAY_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define MAIN_DISPLAY_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define GX_COLOR_ID_BLUE 29
#define MAIN_DISPLAY_COLOR_TABLE_SIZE 30

/* Font ID definitions                                                         */

#define MAIN_DISPLAY_FONT_TABLE_SIZE 4

/* Pixelmap ID definitions                                                     */

#define GX_PIXELMAP_ID_AM_PM_0 5
#define GX_PIXELMAP_ID_AM_PM_1 6
#define GX_PIXELMAP_ID_BATTERY 7
#define GX_PIXELMAP_ID_BATT_NUM_0 8
#define GX_PIXELMAP_ID_BATT_NUM_1 9
#define GX_PIXELMAP_ID_BATT_NUM_2 10
#define GX_PIXELMAP_ID_BATT_NUM_3 11
#define GX_PIXELMAP_ID_BATT_NUM_4 12
#define GX_PIXELMAP_ID_BATT_NUM_5 13
#define GX_PIXELMAP_ID_BATT_NUM_6 14
#define GX_PIXELMAP_ID_BATT_NUM_7 15
#define GX_PIXELMAP_ID_BATT_NUM_8 16
#define GX_PIXELMAP_ID_BATT_NUM_9 17
#define GX_PIXELMAP_ID_BATT_NUM_A 18
#define GX_PIXELMAP_ID_BLUETOOTH 19
#define GX_PIXELMAP_ID_KAL_NUM_0 20
#define GX_PIXELMAP_ID_KAL_NUM_1 21
#define GX_PIXELMAP_ID_KAL_NUM_2 22
#define GX_PIXELMAP_ID_KAL_NUM_3 23
#define GX_PIXELMAP_ID_KAL_NUM_4 24
#define GX_PIXELMAP_ID_KAL_NUM_5 25
#define GX_PIXELMAP_ID_KAL_NUM_6 26
#define GX_PIXELMAP_ID_KAL_NUM_7 27
#define GX_PIXELMAP_ID_KAL_NUM_8 28
#define GX_PIXELMAP_ID_KAL_NUM_9 29
#define GX_PIXELMAP_ID_KAL_NUM_MINUS 30
#define GX_PIXELMAP_ID_SOUND 31
#define GX_PIXELMAP_ID_WIFI 32
#define GX_PIXELMAP_ID__ 33
#define GX_PIXELMAP_ID_BATT_ID 34
#define GX_PIXELMAP_ID_HOUR_ID 35
#define GX_PIXELMAP_ID_MIN_ID 36
#define GX_PIXELMAP_ID_MONTH_1 37
#define GX_PIXELMAP_ID_MONTH_2 38
#define GX_PIXELMAP_ID_MONTH_3 39
#define GX_PIXELMAP_ID_MONTH_4 40
#define GX_PIXELMAP_ID_MONTH_5 41
#define GX_PIXELMAP_ID_MONTH_6 42
#define GX_PIXELMAP_ID_MONTH_7 43
#define GX_PIXELMAP_ID_MONTH_8 44
#define GX_PIXELMAP_ID_MONTH_9 45
#define GX_PIXELMAP_ID_MONTH_A 46
#define GX_PIXELMAP_ID_MONTH_B 47
#define GX_PIXELMAP_ID_MONTH_C 48
#define GX_PIXELMAP_ID_NUM_0 49
#define GX_PIXELMAP_ID_NUM_1 50
#define GX_PIXELMAP_ID_NUM_2 51
#define GX_PIXELMAP_ID_NUM_3 52
#define GX_PIXELMAP_ID_NUM_4 53
#define GX_PIXELMAP_ID_NUM_5 54
#define GX_PIXELMAP_ID_NUM_6 55
#define GX_PIXELMAP_ID_NUM_7 56
#define GX_PIXELMAP_ID_NUM_8 57
#define GX_PIXELMAP_ID_NUM_9 58
#define GX_PIXELMAP_ID_NUM_A 59
#define GX_PIXELMAP_ID_NUM_B 60
#define GX_PIXELMAP_ID_SEC_ID 61
#define GX_PIXELMAP_ID_WEEK_1 62
#define GX_PIXELMAP_ID_WEEK_2 63
#define GX_PIXELMAP_ID_WEEK_3 64
#define GX_PIXELMAP_ID_WEEK_4 65
#define GX_PIXELMAP_ID_WEEK_5 66
#define GX_PIXELMAP_ID_WEEK_6 67
#define GX_PIXELMAP_ID_WEEK_7 68
#define MAIN_DISPLAY_PIXELMAP_TABLE_SIZE 69

/* String Ids                                                                  */

#define GX_STRING_ID_STRING_1 1
#define GX_STRING_ID_STRING_2 2
#define GX_STRING_ID_STRING_3 3
#define MAIN_DISPLAY_STRING_TABLE_SIZE 4

#endif                                       /* sentry                         */
