/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: remind.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "remind.pb-c.h"
void   remind__call__init
                     (Remind__Call         *message)
{
  static const Remind__Call init_value = REMIND__CALL__INIT;
  *message = init_value;
}
size_t remind__call__get_packed_size
                     (const Remind__Call *message)
{
  assert(message->base.descriptor == &remind__call__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t remind__call__pack
                     (const Remind__Call *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &remind__call__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t remind__call__pack_to_buffer
                     (const Remind__Call *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &remind__call__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Remind__Call *
       remind__call__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Remind__Call *)
     protobuf_c_message_unpack (&remind__call__descriptor,
                                allocator, len, data);
}
void   remind__call__free_unpacked
                     (Remind__Call *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &remind__call__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   remind__message__init
                     (Remind__Message         *message)
{
  static const Remind__Message init_value = REMIND__MESSAGE__INIT;
  *message = init_value;
}
size_t remind__message__get_packed_size
                     (const Remind__Message *message)
{
  assert(message->base.descriptor == &remind__message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t remind__message__pack
                     (const Remind__Message *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &remind__message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t remind__message__pack_to_buffer
                     (const Remind__Message *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &remind__message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Remind__Message *
       remind__message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Remind__Message *)
     protobuf_c_message_unpack (&remind__message__descriptor,
                                allocator, len, data);
}
void   remind__message__free_unpacked
                     (Remind__Message *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &remind__message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   remind__battery__init
                     (Remind__Battery         *message)
{
  static const Remind__Battery init_value = REMIND__BATTERY__INIT;
  *message = init_value;
}
size_t remind__battery__get_packed_size
                     (const Remind__Battery *message)
{
  assert(message->base.descriptor == &remind__battery__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t remind__battery__pack
                     (const Remind__Battery *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &remind__battery__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t remind__battery__pack_to_buffer
                     (const Remind__Battery *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &remind__battery__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Remind__Battery *
       remind__battery__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Remind__Battery *)
     protobuf_c_message_unpack (&remind__battery__descriptor,
                                allocator, len, data);
}
void   remind__battery__free_unpacked
                     (Remind__Battery *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &remind__battery__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor remind__call__field_descriptors[3] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Remind__Call, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phone",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Remind__Call, phone),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "people",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Remind__Call, people),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned remind__call__field_indices_by_name[] = {
  2,   /* field[2] = people */
  1,   /* field[1] = phone */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange remind__call__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor remind__call__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "remind.Call",
  "Call",
  "Remind__Call",
  "remind",
  sizeof(Remind__Call),
  3,
  remind__call__field_descriptors,
  remind__call__field_indices_by_name,
  1,  remind__call__number_ranges,
  (ProtobufCMessageInit) remind__call__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue remind__message__type__enum_values_by_number[4] =
{
  { "TEXT", "REMIND__MESSAGE__TYPE__TEXT", 0 },
  { "FACEBOOK", "REMIND__MESSAGE__TYPE__FACEBOOK", 1 },
  { "WECHAT", "REMIND__MESSAGE__TYPE__WECHAT", 2 },
  { "QQ", "REMIND__MESSAGE__TYPE__QQ", 3 },
};
static const ProtobufCIntRange remind__message__type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex remind__message__type__enum_values_by_name[4] =
{
  { "FACEBOOK", 1 },
  { "QQ", 3 },
  { "TEXT", 0 },
  { "WECHAT", 2 },
};
const ProtobufCEnumDescriptor remind__message__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "remind.Message.Type",
  "Type",
  "Remind__Message__Type",
  "remind",
  4,
  remind__message__type__enum_values_by_number,
  4,
  remind__message__type__enum_values_by_name,
  1,
  remind__message__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const Remind__Message__Type remind__message__type__default_value = REMIND__MESSAGE__TYPE__TEXT;
static const ProtobufCFieldDescriptor remind__message__field_descriptors[5] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Remind__Message, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Remind__Message, type),
    &remind__message__type__descriptor,
    &remind__message__type__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phone",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Remind__Message, phone),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "text",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Remind__Message, text),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "people",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Remind__Message, people),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned remind__message__field_indices_by_name[] = {
  4,   /* field[4] = people */
  2,   /* field[2] = phone */
  3,   /* field[3] = text */
  0,   /* field[0] = timestamp */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange remind__message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor remind__message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "remind.Message",
  "Message",
  "Remind__Message",
  "remind",
  sizeof(Remind__Message),
  5,
  remind__message__field_descriptors,
  remind__message__field_indices_by_name,
  1,  remind__message__number_ranges,
  (ProtobufCMessageInit) remind__message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor remind__battery__field_descriptors[1] =
{
  {
    "percent",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Remind__Battery, percent),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned remind__battery__field_indices_by_name[] = {
  0,   /* field[0] = percent */
};
static const ProtobufCIntRange remind__battery__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor remind__battery__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "remind.Battery",
  "Battery",
  "Remind__Battery",
  "remind",
  sizeof(Remind__Battery),
  1,
  remind__battery__field_descriptors,
  remind__battery__field_indices_by_name,
  1,  remind__battery__number_ranges,
  (ProtobufCMessageInit) remind__battery__init,
  NULL,NULL,NULL    /* reserved[123] */
};
