/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: remind.proto */

#ifndef PROTOBUF_C_remind_2eproto__INCLUDED
#define PROTOBUF_C_remind_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Remind__Call Remind__Call;
typedef struct _Remind__Message Remind__Message;
typedef struct _Remind__Battery Remind__Battery;


/* --- enums --- */

typedef enum _Remind__Message__Type {
  /*
   * Text message 
   */
  REMIND__MESSAGE__TYPE__TEXT = 0,
  /*
   * Facebook message 
   */
  REMIND__MESSAGE__TYPE__FACEBOOK = 1,
  REMIND__MESSAGE__TYPE__WECHAT = 2,
  REMIND__MESSAGE__TYPE__QQ = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(REMIND__MESSAGE__TYPE)
} Remind__Message__Type;

/* --- messages --- */

struct  _Remind__Call
{
  ProtobufCMessage base;
  /*
   *Time Stamp
   */
  uint32_t timestamp;
  /*
   *Phone number
   */
  char *phone;
  /*
   *Contact name
   */
  char *people;
};
#define REMIND__CALL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&remind__call__descriptor) \
    , 0, NULL, NULL }


struct  _Remind__Message
{
  ProtobufCMessage base;
  /*
   *Time Stamp
   */
  uint32_t timestamp;
  Remind__Message__Type type;
  /*
   *Phone number
   */
  char *phone;
  /*
   *Message text
   */
  char *text;
  /*
   *Contact name
   */
  char *people;
};
#define REMIND__MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&remind__message__descriptor) \
    , 0, REMIND__MESSAGE__TYPE__TEXT, NULL, NULL, NULL }


struct  _Remind__Battery
{
  ProtobufCMessage base;
  /*
   *Low power threshold
   */
  uint32_t percent;
};
#define REMIND__BATTERY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&remind__battery__descriptor) \
    , 0 }


/* Remind__Call methods */
void   remind__call__init
                     (Remind__Call         *message);
size_t remind__call__get_packed_size
                     (const Remind__Call   *message);
size_t remind__call__pack
                     (const Remind__Call   *message,
                      uint8_t             *out);
size_t remind__call__pack_to_buffer
                     (const Remind__Call   *message,
                      ProtobufCBuffer     *buffer);
Remind__Call *
       remind__call__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   remind__call__free_unpacked
                     (Remind__Call *message,
                      ProtobufCAllocator *allocator);
/* Remind__Message methods */
void   remind__message__init
                     (Remind__Message         *message);
size_t remind__message__get_packed_size
                     (const Remind__Message   *message);
size_t remind__message__pack
                     (const Remind__Message   *message,
                      uint8_t             *out);
size_t remind__message__pack_to_buffer
                     (const Remind__Message   *message,
                      ProtobufCBuffer     *buffer);
Remind__Message *
       remind__message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   remind__message__free_unpacked
                     (Remind__Message *message,
                      ProtobufCAllocator *allocator);
/* Remind__Battery methods */
void   remind__battery__init
                     (Remind__Battery         *message);
size_t remind__battery__get_packed_size
                     (const Remind__Battery   *message);
size_t remind__battery__pack
                     (const Remind__Battery   *message,
                      uint8_t             *out);
size_t remind__battery__pack_to_buffer
                     (const Remind__Battery   *message,
                      ProtobufCBuffer     *buffer);
Remind__Battery *
       remind__battery__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   remind__battery__free_unpacked
                     (Remind__Battery *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Remind__Call_Closure)
                 (const Remind__Call *message,
                  void *closure_data);
typedef void (*Remind__Message_Closure)
                 (const Remind__Message *message,
                  void *closure_data);
typedef void (*Remind__Battery_Closure)
                 (const Remind__Battery *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor remind__call__descriptor;
extern const ProtobufCMessageDescriptor remind__message__descriptor;
extern const ProtobufCEnumDescriptor    remind__message__type__descriptor;
extern const ProtobufCMessageDescriptor remind__battery__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_remind_2eproto__INCLUDED */
