/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: setting.proto */

#ifndef PROTOBUF_C_setting_2eproto__INCLUDED
#define PROTOBUF_C_setting_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Setting__Time Setting__Time;
typedef struct _Setting__Alarm Setting__Alarm;
typedef struct _Setting__Alarm__Body Setting__Alarm__Body;


/* --- enums --- */


/* --- messages --- */

struct  _Setting__Time
{
  ProtobufCMessage base;
  uint32_t year;
  uint32_t mon;
  uint32_t day;
  uint32_t hour;
  uint32_t min;
  uint32_t sec;
};
#define SETTING__TIME__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&setting__time__descriptor) \
    , 0, 0, 0, 0, 0, 0 }


struct  _Setting__Alarm__Body
{
  ProtobufCMessage base;
  uint32_t hour;
  uint32_t min;
  uint32_t sec;
  /*
   *Monday(0x01), Tuesday(0x02),..., Sunday(0x40)
   */
  uint32_t weekbits;
  protobuf_c_boolean repeat;
};
#define SETTING__ALARM__BODY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&setting__alarm__body__descriptor) \
    , 0, 0, 0, 0, 0 }


struct  _Setting__Alarm
{
  ProtobufCMessage base;
  size_t n_entities;
  Setting__Alarm__Body **entities;
};
#define SETTING__ALARM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&setting__alarm__descriptor) \
    , 0,NULL }


/* Setting__Time methods */
void   setting__time__init
                     (Setting__Time         *message);
size_t setting__time__get_packed_size
                     (const Setting__Time   *message);
size_t setting__time__pack
                     (const Setting__Time   *message,
                      uint8_t             *out);
size_t setting__time__pack_to_buffer
                     (const Setting__Time   *message,
                      ProtobufCBuffer     *buffer);
Setting__Time *
       setting__time__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   setting__time__free_unpacked
                     (Setting__Time *message,
                      ProtobufCAllocator *allocator);
/* Setting__Alarm__Body methods */
void   setting__alarm__body__init
                     (Setting__Alarm__Body         *message);
/* Setting__Alarm methods */
void   setting__alarm__init
                     (Setting__Alarm         *message);
size_t setting__alarm__get_packed_size
                     (const Setting__Alarm   *message);
size_t setting__alarm__pack
                     (const Setting__Alarm   *message,
                      uint8_t             *out);
size_t setting__alarm__pack_to_buffer
                     (const Setting__Alarm   *message,
                      ProtobufCBuffer     *buffer);
Setting__Alarm *
       setting__alarm__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   setting__alarm__free_unpacked
                     (Setting__Alarm *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Setting__Time_Closure)
                 (const Setting__Time *message,
                  void *closure_data);
typedef void (*Setting__Alarm__Body_Closure)
                 (const Setting__Alarm__Body *message,
                  void *closure_data);
typedef void (*Setting__Alarm_Closure)
                 (const Setting__Alarm *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor setting__time__descriptor;
extern const ProtobufCMessageDescriptor setting__alarm__descriptor;
extern const ProtobufCMessageDescriptor setting__alarm__body__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_setting_2eproto__INCLUDED */
