/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: setting.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "setting.pb-c.h"
void   setting__time__init
                     (Setting__Time         *message)
{
  static const Setting__Time init_value = SETTING__TIME__INIT;
  *message = init_value;
}
size_t setting__time__get_packed_size
                     (const Setting__Time *message)
{
  assert(message->base.descriptor == &setting__time__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t setting__time__pack
                     (const Setting__Time *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &setting__time__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t setting__time__pack_to_buffer
                     (const Setting__Time *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &setting__time__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Setting__Time *
       setting__time__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Setting__Time *)
     protobuf_c_message_unpack (&setting__time__descriptor,
                                allocator, len, data);
}
void   setting__time__free_unpacked
                     (Setting__Time *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &setting__time__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   setting__alarm__body__init
                     (Setting__Alarm__Body         *message)
{
  static const Setting__Alarm__Body init_value = SETTING__ALARM__BODY__INIT;
  *message = init_value;
}
void   setting__alarm__init
                     (Setting__Alarm         *message)
{
  static const Setting__Alarm init_value = SETTING__ALARM__INIT;
  *message = init_value;
}
size_t setting__alarm__get_packed_size
                     (const Setting__Alarm *message)
{
  assert(message->base.descriptor == &setting__alarm__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t setting__alarm__pack
                     (const Setting__Alarm *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &setting__alarm__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t setting__alarm__pack_to_buffer
                     (const Setting__Alarm *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &setting__alarm__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Setting__Alarm *
       setting__alarm__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Setting__Alarm *)
     protobuf_c_message_unpack (&setting__alarm__descriptor,
                                allocator, len, data);
}
void   setting__alarm__free_unpacked
                     (Setting__Alarm *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &setting__alarm__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor setting__time__field_descriptors[6] =
{
  {
    "year",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Setting__Time, year),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mon",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Setting__Time, mon),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "day",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Setting__Time, day),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hour",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Setting__Time, hour),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "min",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Setting__Time, min),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sec",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Setting__Time, sec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned setting__time__field_indices_by_name[] = {
  2,   /* field[2] = day */
  3,   /* field[3] = hour */
  4,   /* field[4] = min */
  1,   /* field[1] = mon */
  5,   /* field[5] = sec */
  0,   /* field[0] = year */
};
static const ProtobufCIntRange setting__time__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor setting__time__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "setting.Time",
  "Time",
  "Setting__Time",
  "setting",
  sizeof(Setting__Time),
  6,
  setting__time__field_descriptors,
  setting__time__field_indices_by_name,
  1,  setting__time__number_ranges,
  (ProtobufCMessageInit) setting__time__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor setting__alarm__body__field_descriptors[5] =
{
  {
    "hour",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Setting__Alarm__Body, hour),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "min",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Setting__Alarm__Body, min),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sec",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Setting__Alarm__Body, sec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "weekbits",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Setting__Alarm__Body, weekbits),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "repeat",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Setting__Alarm__Body, repeat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned setting__alarm__body__field_indices_by_name[] = {
  0,   /* field[0] = hour */
  1,   /* field[1] = min */
  4,   /* field[4] = repeat */
  2,   /* field[2] = sec */
  3,   /* field[3] = weekbits */
};
static const ProtobufCIntRange setting__alarm__body__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor setting__alarm__body__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "setting.Alarm.Body",
  "Body",
  "Setting__Alarm__Body",
  "setting",
  sizeof(Setting__Alarm__Body),
  5,
  setting__alarm__body__field_descriptors,
  setting__alarm__body__field_indices_by_name,
  1,  setting__alarm__body__number_ranges,
  (ProtobufCMessageInit) setting__alarm__body__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor setting__alarm__field_descriptors[1] =
{
  {
    "entities",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Setting__Alarm, n_entities),
    offsetof(Setting__Alarm, entities),
    &setting__alarm__body__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned setting__alarm__field_indices_by_name[] = {
  0,   /* field[0] = entities */
};
static const ProtobufCIntRange setting__alarm__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor setting__alarm__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "setting.Alarm",
  "Alarm",
  "Setting__Alarm",
  "setting",
  sizeof(Setting__Alarm),
  1,
  setting__alarm__field_descriptors,
  setting__alarm__field_indices_by_name,
  1,  setting__alarm__number_ranges,
  (ProtobufCMessageInit) setting__alarm__init,
  NULL,NULL,NULL    /* reserved[123] */
};
